<a href="https://colab.research.google.com/github/gc2321/3546-Deep-Learning/blob/main/pytorch/1_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.3.0+cu121'

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [4]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)

print(x)

tensor([1, 2, 3, 4, 5])


In [5]:
print(x.dtype)

torch.int64


In [6]:
# Print the tensor object type
print(type(x))
print(x.type()) # this is more specific!

<class 'torch.Tensor'>
torch.LongTensor


In [7]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [8]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [9]:
# use this to make a copy of arr, no link between arr and tensor
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


Allocate Empty Tensor

In [10]:
torch.empty(4, 2)

tensor([[2.1707e-18, 7.0952e+22],
        [1.7748e+28, 1.8176e+31],
        [7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28]])

In [11]:
torch.zeros(4, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

Random number

In [12]:
# random number of uniform distribution, between 0 - 1
x = torch.rand(4, 3)
print(x)

tensor([[0.8459, 0.0225, 0.1016],
        [0.5601, 0.6500, 0.0563],
        [0.8157, 0.8751, 0.3342],
        [0.0738, 0.2528, 0.4907]])


In [13]:
# standard normal distribution, mean = 0, between -1 to 1
x = torch.randn(4, 3)
print(x)

tensor([[ 0.2319, -0.5036,  0.2559],
        [ 0.0173, -0.9036, -1.9876],
        [ 0.5554,  0.1109, -0.4125],
        [ 0.5420, -0.3405,  0.1254]])


Random number tensors with defined input size

In [14]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [15]:
x2 = torch.randn_like(x)
print(x2)

tensor([[ 1.8265,  0.1686, -0.9363, -0.6162, -0.2670],
        [ 0.5786,  0.4159,  1.9304, -0.6513, -1.1962]])


In [16]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Setting the random seed

In [17]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [18]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


Tensor attributes

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
x.size()

torch.Size([2, 3])

In [21]:
x.device

device(type='cpu')

## Operations

In [22]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [23]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [24]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [25]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Tensor Arithmetic

In [26]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


In [27]:
print(torch.add(a, b))

tensor([5., 7., 9.])


In [28]:
result = torch.empty(3)
torch.add(a, b, out=result)  # equivalent to result=torch.add(a,b)
print(result)

tensor([5., 7., 9.])


In [29]:
# add_ : change 'a' after addition
a.add_(b)  # equivalent to a=torch.add(a,b)
print(a)

tensor([5., 7., 9.])


In [30]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(torch.add(a,b).sum())

tensor(21.)


Dot products

In [31]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b)) # for reference
print()
print(a.dot(b))

tensor([ 4., 10., 18.])

tensor(32.)


In [33]:
# matrix multiplication
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [34]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [35]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [36]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


Euclidian Norm

In [37]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)

In [39]:
# number of elements
x = torch.ones(3,7)
x.numel()

21