<img src="https://github.com/gc2321/3546-Deep-Learning/blob/main/Pierian-Data-Logo.PNG?raw=1">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [1]:
import torch
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [2]:
np.random.seed(42)
torch.manual_seed(42);

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
arr = np.random.randint(0,5,6)
print(arr)



[3 4 2 4 4 1]


### 4. Create a tensor "x" from the array above

In [5]:
x = torch.from_numpy(arr)
print(x)



tensor([3, 4, 2, 4, 4, 1])


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [6]:
x = x.type(torch.int64)
# x = x.type(torch.LongTensor)
print(x.type())



torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [10]:
x = x.view(3,2)
# x = x.reshape(3,2)
# x.resize_(3,2)
print(x)



tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [12]:
print(x[:,1:])
# print(x[:,1])


tensor([[4],
        [4],
        [1]])


In [ ]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [13]:
print(x*x)
# print(x**2)
# print(x.mul(x))
# print(x.pow(2))
# print(torch.mul(x,x))



tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [14]:
y = torch.randint(0,5,(2,3))
print(y)



tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Find the matrix product of x and y

In [15]:
print(x.mm(y))



tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Great job!